name: HTTP/2 Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run tests
      run: |
        python tests/run_test.py | tee test_output.txt
        if grep -q "Error" test_output.txt; then
          echo "Tests failed - found errors"
          exit 1
        else
          echo "All tests passed"
        fi